Jun 1, 2019 1:13:37 PM, Exception was thrown: Can not access the data base.
se.kth.iv1350.POSsystem.view.DataBaseException: Can not access the data base.
	at se.kth.iv1350.POSsystem.controller.Controller.registerItem(Controller.java:57)
	at se.kth.iv1350.POSsystem.view.View.runSampleExecution(View.java:33)
	at se.kth.iv1350.POSsystem.startup.Main.main(Main.java:15)
